version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.25-latest
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
